
{{- $fullName := include "payment-service.fullname" . -}}
{{- $svcPort := .Values.service.port -}}

apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:
  name: {{ $fullName }}

  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1

spec:
  rules:
    - host: payment-service.local

    - http:
        paths:
          - path: /

            pathType: ImplementationSpecific

            backend:
              service:
                name: {{ $fullName }}

                port:
                  number: {{ $svcPort }}
