version: "3"
services:
########################################################
############### Main Services ##########################
########################################################
  cart:
    build: &cart-build
      context: .
    volumes: &cart-volumes
      - .:/app
    ports:
      - "8000:8000"
    depends_on: &cart-depends-on
      - cart-redis
    networks: &cart-networks
      - store-api-network

  cart-redis:
    image: redis:latest
    networks: *cart-networks

########################################################
################ CI Services ###########################
########################################################

  ci: &ci
    build: *cart-build
    volumes: *cart-volumes
    depends_on: *cart-depends-on
    networks: *cart-networks
    command: ["go", "test", "-v", "-vet=off", "./..."]

  spec:
    <<: *ci

#### If we want to run locally we need to create a default network for all the services. 
networks:
  store-api-network:
    external: true
  default:
