name: Catalog CI Pipeline

on:
  pull_request:
    branches:
      - main 
    paths:
      - 'payment/**'
  push:
    branches:
      - 'payment-**'
      - 'payment/**'

defaults:
  run:
    working-directory: ./payment

jobs:
  ci: 
    name: Cart CI 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Test
        run: make ci
