name: Payment CI Pipeline

on:
  pull_request:
    branches:
      - main 
    paths:
      - 'payment/**'
  push:
    branches:
      - 'payment-**'
      - 'payment/**'
    tags: 
      - '*payment'
  workflow_dispatch:
    logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

defaults:
  run:
    working-directory: ./payment

env:
  BUILD_TARGETS: payment-service
  CURRENT_BUILD_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/store-api-payment-service


jobs:
  ci: 
    name: Payment CI 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Test
        run: make ci

  build_deploy_image:
    needs: [ci]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Tag
        run: |
          make build
          docker tag $CURRENT_BUILD_IMAGE_NAME $CURRENT_BUILD_IMAGE_NAME:${{ github.ref_name }} 
          docker tag $CURRENT_BUILD_IMAGE_NAME $CURRENT_BUILD_IMAGE_NAME:${{ github.run_attempt }}

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
            
      - name: Push image to DockerHub
      # Push all tags (-a)
        run: docker push -a $CURRENT_BUILD_IMAGE_NAME
